spring.application.name=restapi

# --------------------------------------------------
# DATABASE CONFIG (PostgreSQL)
# --------------------------------------------------
spring.datasource.url=jdbc:postgresql://ep-odd-cloud-a1yf6xqj-pooler.ap-southeast-1.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VYoNw9IE4jFp
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Logging SQL ???? execute
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.namedparam=DEBUG

# Optional: HikariCP connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JWT Configuration
jwt.secret=a-string-secret-at-least-256-bits-long
jwt.issuer=https://api.mikan-app.com

file.upload-dir=uploads/images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB